# Guide to understand this code
# https://circleci.com/docs/2.0/configuration-reference/

version: 2

jobs:
  simple-job: # Job name
    docker:
      - image: circleci/python:3.8.8
    steps:
      # make repo code availible in the current folder
      - checkout
      # Debug pwd (~/project/)
      - run: |
          pwd
          ls -a
      # Debug shell
      - run: echo $SHELL
      # Debug python
      - run: python -V

  build-and-test:
    docker:
      # Docker container with Miniconda3 installed
      - image: continuumio/miniconda3

    steps:
      - checkout

      # Create conda environment
      - restore_cache:
          keys:
            - test-env
      - run: conda create --quiet --name test-env python=3.8.8
      - save_cache:
          keys:
            - test-env

      # Install dependencies
      - restore_cache:
          keys:
            - test-env-dep-{{ checksum "my_dependencies.txt"}}
            - test-env-dep-      
      - run: conda install -n test-env --file my_dependencies.txt
      - save_cache:
          keys:
            - test-env-dep-{{ checksum "my_dependencies.txt"}}
            - test-env-dep-

      - run: conda list -n test-env

      # # This cmd work but 'conda activate' does not
      # - run: source activate test-environment

workflows:
  version: 2
  main: # Work flow name
    jobs:
      # These jobs will run in parallel
      - simple-job
      - build-and-test
